###
// 获取用户信息接口
GET http://localhost:3000/admin/getUserInfo
Accept: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJhZG1pbiIsImljb24iOm51bGwsImVtYWlsIjpudWxsLCJuaWNrX25hbWUiOm51bGwsImhvbWVfcGF0aCI6Ii9kYXNoYm9hcmQvYW5hbHlzaXMiLCJub3RlIjpudWxsLCJsb2dpbl90aW1lIjpudWxsLCJzdGF0dXMiOnRydWUsImNyZWF0ZV90aW1lIjoiMjAyMi0wMi0xNlQxNTowNDoxMS4wMDBaIiwidXBkYXRlX3RpbWUiOiIyMDIyLTAyLTE2VDE1OjA0OjExLjAwMFoiLCJpYXQiOjE2NDUwMjM4OTksImV4cCI6MTY0NTExMDI5OX0.AZ1MJxc8Nh6YmgR5ya_HgwRMFGVsT3AJBRAGm6tPjJA

###
// 登录接口
POST http://localhost:3000/admin/login
Content-Type: application/json

{
  "username": "admin",
  "password": "123456"
}

###
// 注册接口
POST http://localhost:3000/admin/register
Content-Type: application/json

{
  "username": "admin",
  "password": "123456"
}
